app:
  vector:
    index-name: picindex_images_cloud
    indexVersion: v2
    read-alias: picindex_images_cloud_read
    write-alias: picindex_images_cloud_write
    dimension: 1024
    model-type: CLOUD
  embedding:
    image-input-mode: url
